// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsWmo2VYgNK-_yMqAVRMJnLdkmit1aBY',
    appId: '1:67821362043:web:8794e7ed958a4acba8bbde',
    messagingSenderId: '67821362043',
    projectId: 'flutterboilerplatehub9',
    authDomain: 'flutterboilerplatehub9.firebaseapp.com',
    storageBucket: 'flutterboilerplatehub9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggYRuCQuNyhKZJqAURpA0Ghe3jXfkjbk',
    appId: '1:67821362043:android:3859272ffd4810bba8bbde',
    messagingSenderId: '67821362043',
    projectId: 'flutterboilerplatehub9',
    storageBucket: 'flutterboilerplatehub9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-PX2w8bdX-uW5zNbSHE06Gx4kGyJwShI',
    appId: '1:67821362043:ios:fc31f19ffb17b424a8bbde',
    messagingSenderId: '67821362043',
    projectId: 'flutterboilerplatehub9',
    storageBucket: 'flutterboilerplatehub9.appspot.com',
    iosBundleId: 'com.example.flutterBoilerPlate',
  );
}
